import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  contentContainer: {
    flexGrow: 1,
    padding: 20,
    alignItems: "center",
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#00223A",
    marginBottom: 30,
    marginTop: 10,
  },
  error: {
    color: "#B30E2F",
    fontSize: 14,
    marginBottom: 15,
    textAlign: "center",
    backgroundColor: "rgba(179, 14, 47, 0.1)",
    padding: 10,
    borderRadius: 8,
    width: "100%",
  },
  fieldError: {
    color: "#B30E2F",
    fontSize: 12,
    marginTop: -10,
    marginBottom: 10,
    alignSelf: "flex-start",
    marginLeft: 5,
  },
  inputField: {
    backgroundColor: "#296D9D",
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
    marginBottom: 15,
    width: "100%",
    fontSize: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    color: "#fff",
  },
  inputError: {
    borderWidth: 1,
    borderColor: "#B30E2F",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 15,
  },
  halfWidth: {
    width: "48%",
  },
  dropdownButton: {
    backgroundColor: "#00223A",
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    height: 50,
  },
  dropdownButtoneti: {
    backgroundColor: "#00223A",
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    height: 50,
    marginBottom: 20,
    width: "100%",
  },
  dropdownButtonText: {
    color: "#fff",
    fontSize: 16,
  },
  largeInputField: {
    height: 120,
    textAlignVertical: "top",
    paddingTop: 12,
  },
  hiddenPicker: {
    position: "absolute",
    width: "100%",
    height: "100%",
    opacity: 0,
  },
  registerButton: {
    backgroundColor: "#B30E2F",
    paddingVertical: 15,
    borderRadius: 8,
    width: "90%",
    alignItems: "center",
    marginTop: 30,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  registerButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  caseSelectionContainer: {
    marginVertical: 20,
    width: "100%",
  },
  caseItem: {
    padding: 15,
    backgroundColor: "#f0f0f0",
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  selectedCaseItem: {
    backgroundColor: "#296D9D",
    borderColor: "#296D9D",
  },
  caseItemText: {
    fontSize: 16,
    color: "#333",
  },
  selectedCaseItemText: {
    color: "#fff",
  },
  disabledButton: {
    opacity: 0.5,
  },
  pickerContainer: {
    width: "100%",
    backgroundColor: "#1a1a1a",
    borderRadius: 8,
    marginTop: 4,
    marginBottom: 16,
    overflow: "hidden",
  },
  picker: {
    width: "100%",
    height: 200,
    color: "#fff",
  },
});
