import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  text: {
    fontSize: 32,
    fontWeight: 400,
    color: "white",
  },
  summaryPanel: {
    backgroundColor: "#00223A",
    borderRadius: 15,
    padding: 20,
    marginVertical: 20,
    width: "90%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-around",
  },
  summaryItem: {
    alignItems: "center",
    marginHorizontal: 5,
    marginBottom: 10,
    width: "30%",
  },
  summaryText: {
    color: "#fff",
    fontSize: 14,
    textAlign: "center",
  },
  summaryNumber: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "bold",
  },
  detailsButton: {
    backgroundColor: "#B30E2F",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 15,
    marginTop: 15,
    width: "80%",
    alignItems: "center",
  },
  detailsButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  overviewText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#296D9D",
    marginTop: 20,
    marginBottom: 10,
  },
  bottomButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "90%",
    marginTop: 20,
  },
  bottomButton: {
    backgroundColor: "#00223A",
    borderRadius: 10,
    paddingVertical: 5,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
    width: "45%",
  },
  bottomButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
    textAlign: "center",
  },
});
